#include <boost/exception_ptr.hpp>

int main()
{
    return 0;
}